Feature branch
wintan1418/newsweek-project pull request #1
Opened 2020-10-23 20:57 UTC by wintan1418

this is a pull request for my just concluded bootstrap project

2020-10-24 00:41 UTC, ElijahTobs requested changes
# Status: Changes Required ⚠️ 

### 👍  @wintan1418 You've put in a lot of work in this project but you still need to make corrections before it can be approved.

## Required 🛠️ 

- [ ] The background color used in the header is not the same as yours
- [ ] The space on both left and right of the header is equal, unlike yours
- [ ] Increase the font of the subscribe button and bolden both the `subscribe` button and the `login` button

Original:
![or_bhead](https://user-images.githubusercontent.com/16058470/97062725-1a913880-1594-11eb-8d06-bb5a21f717ae.PNG)

Yours:
![bheader](https://user-images.githubusercontent.com/16058470/97062737-23820a00-1594-11eb-8332-f107d1bca98a.PNG)

- [ ] The button is inside the same box that houses the image
Original:
![right1](https://user-images.githubusercontent.com/16058470/97063012-61336280-1595-11eb-89c6-04a8a572714a.PNG)

Yours:
![w1](https://user-images.githubusercontent.com/16058470/97063028-71e3d880-1595-11eb-9500-1fff530a95f6.PNG)

- [ ] The navigation links are not well-aligned

- [ ] The polygon to the far right of the navbar should also be added

Original:
![r_nav](https://user-images.githubusercontent.com/16058470/97063101-c8e9ad80-1595-11eb-8057-57832a10dc29.PNG)

Yours:
![w_nav](https://user-images.githubusercontent.com/16058470/97063113-d3a44280-1595-11eb-8576-20ab8ee3b709.PNG)

- [ ] The tags `EMMYS`, `U.S.` and `EMMYS` are to be positioned relative to the image, not at the top

 Original:
![ctr](https://user-images.githubusercontent.com/16058470/97063310-df443900-1596-11eb-9e53-6b14437c2f2f.PNG)

Yours:
![ctw](https://user-images.githubusercontent.com/16058470/97063320-ed925500-1596-11eb-9e67-729abaa57ae1.PNG)

- [ ] On a smaller than screen, the` person icon`,` subscribe button` and `hamburger menu `should all be well spaced out

Original:
![nav_ori](https://user-images.githubusercontent.com/16058470/97063628-b4f37b00-1598-11eb-8ad5-f59d5692eb62.PNG)

Yours:
![nav_or2](https://user-images.githubusercontent.com/16058470/97063640-c2a90080-1598-11eb-82d8-87b60b1d518c.PNG)

- [ ] Fix the stylelint errors

2020-10-24 21:01 UTC, ElijahTobs requested changes
# Status: Changes Required ⚠️ 

Well done 💪  on implementing some of the required changes but there's still a little more to do before this project can be approved.

## [Required]

- [ ] The navigation links need to be stretched out the same way it is on the original page
- [ ] The search button and icon under the polygon should be beside the polygon
- [ ] Please, do away with the unnecessary space right below the navigation links and above the trending section

**Original:**
![a1](https://user-images.githubusercontent.com/16058470/97093171-a7de9680-1641-11eb-9401-3238710557bd.PNG)

**Yours**:
![a0](https://user-images.githubusercontent.com/16058470/97093178-b167fe80-1641-11eb-8289-f8d9d216802d.PNG)

- [ ] The button/tag has a very visible text. (You can get `ColorZilla`, a chrome extension used to pick colors from webpages.)
**Original**:
![right1](https://user-images.githubusercontent.com/16058470/97093287-7e723a80-1642-11eb-832c-721198fd45a9.PNG)
**Yours**:
![wrong](https://user-images.githubusercontent.com/16058470/97093303-a19cea00-1642-11eb-8442-47316cf396eb.PNG)

- [ ] The horizontal line covers both the subscribe and newsletter. You should also add a margin or padding before that section
**Original**:
![newsl_1](https://user-images.githubusercontent.com/16058470/97093387-5f27dd00-1643-11eb-9d95-7990e52139b4.PNG)
**Yours**:
![newsl_0](https://user-images.githubusercontent.com/16058470/97093392-67801800-1643-11eb-9b7e-7572949c88d5.PNG)

### Make the following changes and request another review

Happy Coding 💻 

Feel free to reach out to me on:
slack @ElijahTobs
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2020-10-25 19:01 UTC, descholar-ceo requested changes
# Status: Change Required :vertical_traffic_light: :warning: 
## Hello @wintan1418  :handshake: :handshake: :handshake: 
:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
## Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes]
- [ ] Newsweek logo size should change on different screen sizes, currently it's remaining on the same size and consequently, that's spoiling your design

- [ ] Your navbar needs more work, when the screen is between (995 px - 1325 px), your navbar on navigation section, it becomes a mess, you should fix that to make sure that the navigation links and search icon stay on the left side of the polygon, currently it's overlapping

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-10-25 20-31-43](https://user-images.githubusercontent.com/56886064/97115750-23ebe380-1701-11eb-86f4-7d4aba0bef8e.png)| ![Screenshot from 2020-10-25 20-32-35](https://user-images.githubusercontent.com/56886064/97115766-3fef8500-1701-11eb-8df6-9b7d1ac817d5.png)|

:point_right: Could you see the difference :question: :question: :question: (Those screenshots are from a 998px screen)

- [ ] On medium screens and small screens, the navbar is overlapping the main page, fix that

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-10-25 20-36-38](https://user-images.githubusercontent.com/56886064/97115848-ef2c5c00-1701-11eb-96a8-881157743843.png) Could you see that the `top stories` title is hidden?| ![Screenshot from 2020-10-25 20-37-31](https://user-images.githubusercontent.com/56886064/97115866-1125de80-1702-11eb-98c5-84ff9ce0ad80.png)|

- [ ] On small screens, the newsweek logo and the signin&subscribe sections are overlapping each other, please fix that as well

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2020-10-25 20-40-45](https://user-images.githubusercontent.com/56886064/97115908-65c95980-1702-11eb-990c-eb0a8d7926ef.png)| ![Screenshot from 2020-10-25 20-41-44](https://user-images.githubusercontent.com/56886064/97115919-88f40900-1702-11eb-8e6b-f6889969bfdd.png)|

:point_right: Could you see the difference :question: :question: :question: 

- [ ] Try to not use id selectors in your css
- [ ] Try to use the same colors on the inline buttons in the editor's pick (text on the last box on the first row is not visible) :point_right:  this was requested in the previous review

- [ ] your footer looks good, but not the same as the original, try to use the same colors from the original footer, and fix the alignment issues 
- [ ] Don't put your license in .vscode folder, I highly recommend you to remove it from that folder, and put it in root directory of your project, and add .vscode folder on .gitignore, because you don't need to commit that folder on your repo, it's totally unnecessary,  [Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png)
- [ ] Try to make your pull request description more descriptive
- [ ] Implement all changes I suggested in inline comments in your codes,

# [Optional changes]
- [ ] I would recommend you to use main, and footer tags for your respective web content
- [ ] Free signup button and subscribe button should use the same red colors from the original page
- [ ] The image in second article of top stories, should be well aligned (on small screens :point_right:  the alignment issue starts from screens below to 650px)
- [ ] In debate section, the black `VS` circle, should be black and circle, no lines travesal should be visible inside that button
- [ ] Starting from the debate section, you should add some margins on each side, currently the content of the page are touching the edge of screen in small sceens
- [ ] I advice you to try to use different images, not one image repetitively, :point_right:  this will make your clone looks more professional
- [ ] Your commit messages should be in imperative mode or present tense, you should have used `Fix the header section and adjust the border section of the subscribe and newsletter` instead of `fixed the header section and adjusted te border section of the subscribe and newsletter`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

If anything seems to be unclear to you, don't hesitate to contact me for more clarification slack: `@Mugirase Emmanuel` | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2020-10-25 19:01 UTC, descholar-ceo commented on README.md
> +You can freely contribute to this project.
How to contribute to this project? This sentence `You can freely contribute to this project.` is not clear enough for a non-tech user to know how they contribute to your project, try to make it a bit clear

2020-10-25 19:01 UTC, descholar-ceo commented on index.html
> +    -->
If you don't need these codes, you should remove them completely, leaving commented codes from your codebase is a bad practice, try to fix that.

2020-10-26 12:50 UTC, PhillipUg approved these changes
# Status: Project Approved! 🥇 
Congratulations on the hard work and also for trying your best to implement all the changes requested by the previous reviewers. :+1:

#### NOTE: The following suggested changes are not mandatory but are nice to have and once implemented, will make your project look professional and nice 😃 

- [OPTIONAL]: The Navbar is still not yet quite there. Eliminate the space at the end towards the right.

| Original page      | Your page     |
| :------------- | :----------: |
|![screenshot-www newsweek com-2020 10 26-15_23_42](https://user-images.githubusercontent.com/20542425/97172150-a7f4a880-179f-11eb-8824-ead80a506f96.png) | ![screenshot-raw githack com-2020 10 26-15_24_20](https://user-images.githubusercontent.com/20542425/97172102-91e6e800-179f-11eb-9848-bdd7b0ddee8b.png) |

- [OPTIONAL]: Also, the section above `In the magazine` on medium screen size shouldn't be full screen, it should be centered in the middle.

| Original page | Your page |
| :------------- | :----------: |
|![screenshot-www newsweek com-2020 10 26-15_32_16](https://user-images.githubusercontent.com/20542425/97173000-eb034b80-17a0-11eb-8416-c06167fc27d8.png) | ![screenshot-raw githack com-2020 10 26-15_31_08](https://user-images.githubusercontent.com/20542425/97173032-fc4c5800-17a0-11eb-8404-720ca4a3828d.png) |

You can merge this branch into the master branch when you're done making the necessary changes and go on to your next project.

:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

2020-10-26 13:07 UTC, merged